version: '3.3'
services:
  elasticmq:
    image: softwaremill/elasticmq-native
    ports:
      - '9324:9324'
      - '9325:9325'
    volumes:
      - ./docker/volumes/elasticmq/elasticmq.conf:/opt/elasticmq.conf
  mysql:
    image: mysql:8
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: 'omnitrade_orders'
      MYSQL_ROOT_PASSWORD: 'Team3$$'
    ports:
      - '3306:3306'
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
  accounts:
    image: maven:3.8-jdk-11
    depends_on:
      - mysql
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - |
        cd /var/www/app
        mvn -f ./02-account-mgt-service/pom.xml -B --no-transfer-progress -Dmaven.test.skip=true install
        mvn -f ./02-account-mgt-service/pom.xml -e -P docker spring-boot:run
    ports:
      - '8081:8080'
    volumes:
      - ./back-end/project-capstone/02-nus-account-mgt-service:/var/www/app
      - maven-repository:/root/.m2
  orders:
    image: maven:3.8-jdk-11
    depends_on:
      - accounts
      - mysql
      - elasticmq
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - |
        cd /var/www/app
        mvn -f ./03-order-matching-service-api/pom.xml -B --no-transfer-progress -Dmaven.test.skip=true install
        mvn -f ./03-order-matching-service-api/pom.xml package
        mvn -f ./03-order-matching-service/pom.xml -B --no-transfer-progress -Dmaven.test.skip=true install
        mvn -f ./03-order-matching-service/pom.xml -e -P docker spring-boot:run
    ports:
      - '8080:8080'
    volumes:
      - ./back-end/project-capstone/03-nus-order-matching-service:/var/www/app
      - maven-repository:/root/.m2

volumes:
  maven-repository:
    external: false
