server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/omnitrade_accounts?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: Team3$
    pool:
      name: order-mysql
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"