server:
  port: ${PORT:8080}

spring:
  profiles:
    active: @activatedProperties@
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # For deployment use
    url: jdbc:mysql://host_is_ignored/account_service_db?cloudSqlInstance=kianming1988:asia-southeast1:ordermatchingsvc&socketFactory=com.google.cloud.sql.mysql.SocketFactory&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    # For development using VPN connection
    # url: jdbc:mysql://10.32.176.3:3306/account_service_db?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: ordermatching
    password: Team3$
    pool:
      name: order-mysql
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"