name: Deploy Frontend to Production
on:
  push:
    branches:
      - production/frontend

env:
  DEPLOY_DIRECTORY: /var/www/swe5005/frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd front-end
          npm install
      - name: Generate build
        run: |
          cd front-end
          npm run build
        # # Disabling CI env var as this is staging workflow
        # env:
        #   CI: false
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: production-deploy
          path: front-end/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: production-deploy
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avzb --backup-dir=$DEPLOY_DIRECTORY../frontend_backup --delete ./ ${{ secrets.STAGING_SSH_USERNAME }}@${{ secrets.STAGING_HOST }}:$DEPLOY_DIRECTORY
      - name: Timestamping deployment
        run: |
          ssh ${{ secrets.STAGING_SSH_USERNAME }}@${{ secrets.STAGING_HOST }} \
          " \
            cd $DEPLOY_DIRECTORY \
            echo "Commit ${{ github.sha }} deployed at $(TZ=":Asia/Singapore" date)" > deployment_info.txt \
          "
