name: Deploy Backend to Production
on:
  push:
    branches:
      - production/backend
      - devops/test

env:
  DEPLOY_DIRECTORY: /var/www/swe5005/deploy/frontend

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"

      - name: Set AWS Crdentials
        run: |
          find ./back-end/ -name "*.yml" -exec sed -i "s@__AWS_ACCESS_KEY__@${{ secrets.AWS_ACCESS_KEY }}@g" {} +
          find ./back-end/ -name "*.yml" -exec sed -i 's@__AWS_SECRET_KEY__@${{ secrets.AWS_SECRET_KEY }}@g' {} +

      - name: Deploy with rsync
        run: |
          rsync -avzb ./ ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_APP_HOST }}:$DEPLOY_DIRECTORY

      - name: Timestamping deployment
        run: |
          ssh ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_APP_HOST }} \
          " \
            cd $DEPLOY_DIRECTORY && \
            echo "Commit ${{ github.sha }} deployed at $(TZ=":Asia/Singapore" date)" > deployment_info.txt \
          "
